# Generated by Django 4.1.11 on 2023-11-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0002_alter_word_laymans"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="phonetic",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
