# Generated by Django 4.1.11 on 2023-11-29 20:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("engine", "0003_word_phonetic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="phonetic",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), blank=True, size=None
            ),
        ),
    ]
